  name: build spring backend
  on:
    push:
      branches:
        - develop
    pull_request:
      branches:
        - develop

  jobs:
    build-backend:
      name: build and deploy backend
      runs-on: ubuntu-20.04
      defaults:
        run:
          working-directory: ./sistema-bancario-backend

      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: resolve dependencies
          run: mvn clean install -DskipTests=true

        - name: unit tests
          run: mvn -B test --file pom.xml

        - name: build the app
          run: mvn -B package -DskipTests=true --file pom.xml

        - name: tag commit
          id: create_tag
          run: |
            TAG_NAME="build-$(date +%s)"
            echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME