  name: build, run static analysis and test for release 
  on:
    push:
        tags: 
          - 'rc-*'
  jobs:
    build-backend:
      name: build and static analysis backend
      runs-on: ubuntu-20.04
      permissions: write-all
      defaults:
        run:
          working-directory: ./sistema-bancario-backend

      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 17

        - name: resolve dependencies
          run: mvn clean install -DskipTests=true

        - name: Run Codacy Analysis CLI
          uses: codacy/codacy-analysis-cli-action@master

        - name: unit tests
          run: mvn -B test --file pom.xml

        - name: build the app
          run: mvn -B package -DskipTests=true --file pom.xml

        # - name: compress files
        #   run: |
        #     version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        #     zip -r "rc-$version.zip" target/sistema-bancario-backend-1.0-SNAPSHOT.jar

        - name: upload artifact
          uses: actions/upload-artifact@v3
          with: 
            name: projetogcm.jar
            path: "sistema-bancario-backend/target/sistema-bancario-backend-1.0-SNAPSHOT.jar"
